import type { Product, StockBatch, Sale, Supplier } from "./types"

export const mockProducts: Product[] = [
  {
    _id: "acetaminofen-500mg",
    name: "Acetaminofén 500mg",
    category: "analgésico",
    principio_activo: "Paracetamol (Acetaminofén)",
    descripcion:
      "Indicaciones: Alivio del dolor leve a moderado y reducción de la fiebre. Dosificación: Adultos: 500 mg cada 4-6 horas según sea necesario; no exceder 4 g/24 h. Niños: ajustar según peso y presentación pediátrica.",
    image_url: "/pharmacy-product.jpg",
    supplier: "Distribuidora Farmacéutica Guatemala",
    presentations: [
      {
        presentation_name: "unidad",
        units: 1,
        cost: 0.45,
        price: 0.6,
        profit_percent: 0.15,
        sku: "ACE-U-01",
      },
      {
        presentation_name: "blister",
        units: 8,
        cost: 2.8,
        price: 3.5,
        profit_percent: 0.2,
        sku: "ACE-B-01",
      },
      {
        presentation_name: "caja",
        units: 80,
        cost: 18.75,
        price: 25.0,
        profit_percent: 0.25,
        sku: "ACE-C-01",
      },
    ],
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-01-15"),
  },
  {
    _id: "ibuprofeno-400mg",
    name: "Ibuprofeno 400mg",
    category: "antiinflamatorio",
    principio_activo: "Ibuprofeno",
    descripcion:
      "Indicaciones: Antiinflamatorio no esteroideo (AINE) para dolor, inflamación y fiebre. Dosificación: Adultos: 400 mg cada 4-6 horas; no exceder 1200 mg/día sin supervisión médica.",
    image_url: "/pharmacy-product.jpg",
    supplier: "Distribuidora Farmacéutica Guatemala",
    presentations: [
      {
        presentation_name: "unidad",
        units: 1,
        cost: 0.5,
        price: 0.7,
        profit_percent: 0.2,
        sku: "IBU-U-01",
      },
      {
        presentation_name: "blister",
        units: 10,
        cost: 4.0,
        price: 5.5,
        profit_percent: 0.27,
        sku: "IBU-B-01",
      },
      {
        presentation_name: "caja",
        units: 100,
        cost: 30.0,
        price: 42.0,
        profit_percent: 0.29,
        sku: "IBU-C-01",
      },
    ],
    created_at: new Date("2024-02-10"),
    updated_at: new Date("2024-02-10"),
  },
  {
    _id: "amoxicilina-500mg",
    name: "Amoxicilina 500mg",
    category: "antibiótico",
    principio_activo: "Amoxicilina",
    descripcion:
      "Indicaciones: Antibiótico de amplio espectro para infecciones bacterianas. Dosificación: Adultos: 500 mg cada 8 horas durante 7-10 días según prescripción médica.",
    image_url: "/pharmacy-product.jpg",
    supplier: "Laboratorios Médicos S.A.",
    presentations: [
      {
        presentation_name: "unidad",
        units: 1,
        cost: 0.8,
        price: 1.2,
        profit_percent: 0.33,
        sku: "AMX-U-01",
      },
      {
        presentation_name: "blister",
        units: 12,
        cost: 8.5,
        price: 12.0,
        profit_percent: 0.29,
        sku: "AMX-B-01",
      },
      {
        presentation_name: "caja",
        units: 24,
        cost: 16.0,
        price: 22.0,
        profit_percent: 0.27,
        sku: "AMX-C-01",
      },
    ],
    created_at: new Date("2024-03-05"),
    updated_at: new Date("2024-03-05"),
  },
  {
    _id: "loratadina-10mg",
    name: "Loratadina 10mg",
    category: "antihistamínico",
    principio_activo: "Loratadina",
    descripcion:
      "Indicaciones: Antihistamínico para alergias estacionales y urticaria. Dosificación: Adultos y niños mayores de 12 años: 10 mg una vez al día.",
    image_url: "/pharmacy-product.jpg",
    supplier: "Distribuidora Farmacéutica Guatemala",
    presentations: [
      {
        presentation_name: "unidad",
        units: 1,
        cost: 0.35,
        price: 0.5,
        profit_percent: 0.3,
        sku: "LOR-U-01",
      },
      {
        presentation_name: "blister",
        units: 10,
        cost: 2.8,
        price: 4.0,
        profit_percent: 0.3,
        sku: "LOR-B-01",
      },
    ],
    created_at: new Date("2024-04-12"),
    updated_at: new Date("2024-04-12"),
  },
]

export const mockStockBatches: StockBatch[] = [
  {
    _id: "batch-ACE-2025-01",
    product_id: "acetaminofen-500mg",
    lot_code: "L2025A",
    expiration_date: new Date("2026-05-30"),
    purchase_date: new Date("2025-01-20"),
    stock_units: 800,
    cost_per_unit: 0.1875,
    location: "farmacia",
    created_at: new Date("2025-01-20"),
    updated_at: new Date("2025-01-20"),
  },
  {
    _id: "batch-ACE-2025-02",
    product_id: "acetaminofen-500mg",
    lot_code: "L2025B",
    expiration_date: new Date("2026-08-15"),
    purchase_date: new Date("2025-02-10"),
    stock_units: 640,
    cost_per_unit: 0.19,
    location: "farmacia",
    created_at: new Date("2025-02-10"),
    updated_at: new Date("2025-02-10"),
  },
  {
    _id: "batch-IBU-2025-01",
    product_id: "ibuprofeno-400mg",
    lot_code: "I2025A",
    expiration_date: new Date("2026-06-20"),
    purchase_date: new Date("2025-01-15"),
    stock_units: 1000,
    cost_per_unit: 0.3,
    location: "farmacia",
    created_at: new Date("2025-01-15"),
    updated_at: new Date("2025-01-15"),
  },
  {
    _id: "batch-AMX-2025-01",
    product_id: "amoxicilina-500mg",
    lot_code: "A2025A",
    expiration_date: new Date("2026-03-10"),
    purchase_date: new Date("2025-01-05"),
    stock_units: 480,
    cost_per_unit: 0.67,
    location: "bodega",
    created_at: new Date("2025-01-05"),
    updated_at: new Date("2025-01-05"),
  },
  {
    _id: "batch-LOR-2025-01",
    product_id: "loratadina-10mg",
    lot_code: "LT2025A",
    expiration_date: new Date("2026-09-25"),
    purchase_date: new Date("2025-02-01"),
    stock_units: 600,
    cost_per_unit: 0.28,
    location: "farmacia",
    created_at: new Date("2025-02-01"),
    updated_at: new Date("2025-02-01"),
  },
]

export const mockSales: Sale[] = [
  {
    _id: "sale-0001",
    sale_name: "Venta Mathew 01",
    datetime: new Date("2025-11-27T19:45:00Z"),
    day_of_week: "jueves",
    shift: "noche",
    items: [
      {
        product_id: "acetaminofen-500mg",
        presentation_name: "blister",
        qty: 2,
        units_deducted: 16,
        batch_id: "batch-ACE-2025-01",
        price_unit: 3.5,
        profit_percent: 0.2,
        subtotal: 7.0,
        batch_cost_per_unit: 0.1875,
        real_cost: 3.0,
        real_profit: 4.0,
      },
    ],
    total: 7.0,
    payment_method: "efectivo",
    created_at: new Date("2025-11-27T19:45:00Z"),
  },
  {
    _id: "sale-0002",
    sale_name: "Venta Cliente 02",
    datetime: new Date("2025-11-28T10:30:00Z"),
    day_of_week: "viernes",
    shift: "mañana",
    items: [
      {
        product_id: "ibuprofeno-400mg",
        presentation_name: "blister",
        qty: 1,
        units_deducted: 10,
        batch_id: "batch-IBU-2025-01",
        price_unit: 5.5,
        profit_percent: 0.27,
        subtotal: 5.5,
        batch_cost_per_unit: 0.3,
        real_cost: 3.0,
        real_profit: 2.5,
      },
      {
        product_id: "loratadina-10mg",
        presentation_name: "blister",
        qty: 1,
        units_deducted: 10,
        batch_id: "batch-LOR-2025-01",
        price_unit: 4.0,
        profit_percent: 0.3,
        subtotal: 4.0,
        batch_cost_per_unit: 0.28,
        real_cost: 2.8,
        real_profit: 1.2,
      },
    ],
    total: 9.5,
    payment_method: "tarjeta",
    created_at: new Date("2025-11-28T10:30:00Z"),
  },
  {
    _id: "sale-0003",
    sale_name: "Venta Cliente 03",
    datetime: new Date("2025-11-28T15:20:00Z"),
    day_of_week: "viernes",
    shift: "tarde",
    items: [
      {
        product_id: "acetaminofen-500mg",
        presentation_name: "caja",
        qty: 1,
        units_deducted: 80,
        batch_id: "batch-ACE-2025-01",
        price_unit: 25.0,
        profit_percent: 0.25,
        subtotal: 25.0,
        batch_cost_per_unit: 0.1875,
        real_cost: 15.0,
        real_profit: 10.0,
      },
    ],
    total: 25.0,
    payment_method: "transferencia",
    created_at: new Date("2025-11-28T15:20:00Z"),
  },
]

export const mockSuppliers: Supplier[] = [
  {
    _id: "supplier-001",
    name: "Distribuidora Farmacéutica Guatemala",
    email: "ventas@distfarmagt.com",
    phone: "+502 2334-5678",
    address: "Zona 10, Ciudad de Guatemala",
    products: ["acetaminofen-500mg", "ibuprofeno-400mg", "loratadina-10mg"],
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-01-01"),
  },
  {
    _id: "supplier-002",
    name: "Laboratorios Médicos S.A.",
    email: "contacto@labmedicos.com",
    phone: "+502 2445-6789",
    address: "Zona 9, Ciudad de Guatemala",
    products: ["amoxicilina-500mg"],
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-01-01"),
  },
]
